name: 'Check Duplicate DMI Icon States'
description: 'Detects that DMIs in folders do not have duplicate icon states'
branding:
  icon: 'image'  
  color: 'blue'
inputs:
  GITHUB_TOKEN:
    description: A GITHUB_TOKEN to fetch the tool
    required: true
  folders_to_search:
    description: 'Folders to search, comma delineated (default: root folder)'
    default: '.'
  flags:
    description: Put other flags for the duplicate checker here
    default: '--warn-read --actions-fmt'
  version:
    description: 'Version of the tool to use (default: latest)'
    default: 'v1.0.6'
runs:
  using: "composite"
  steps:
    - name: Install Duplicate Checker
      uses: jaxxstorm/action-install-gh-release@v2.0.0
      with:
        repo: spacestation13/dmi-duplicate-state-checker
        tag: ${{ inputs.version }}
        cache: enable
        arch: x86_64
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - run: |
        os_str=$(echo 'console.log("${{ runner.os }}".toLowerCase())' | node -);
        /opt/hostedtoolcache/spacestation13/dmi-duplicate-state-checker/${{ inputs.version }}/${os_str}-x86_64/dmi-duplicate-state-checker -p ${{ inputs.folders_to_search }} ${{ inputs.flags }}
      shell: bash
